In [1]:
import pandas as pd

In [2]:
def concat_file(files):
    lfs = []
    for path in files:
        lfs.append(pd.read_csv("Data/"+path, skipinitialspace=True))
    return pd.concat(lfs)

In [3]:
listingsFiles = ["barcelona_listings.csv","berlin_listings_filtered.csv","madrid_listings_filtered.csv"]
listings = concat_file(listingsFiles).rename(columns={
    'host_id':'user_id',
    'host_name':'user_name'}).set_index('id')

In [56]:
def find_different_objects(listing, attribute, selected = False):
    values = listing[attribute]
    values = values.drop_duplicates()
    size = values.shape[0]
    if (selected or size <= 30):
        print(values)
    return values.shape[0]

In [53]:
tmp = []
for attribute in list(listings.columns.values):
    tmp.append(attribute +":"+ str(find_different_objects(listings, attribute)))

id
18666           within an hour
26033978          within a day
32711                      NaN
36763       within a few hours
7047052     a few days or more
Name: host_response_time, dtype: object
id
18666      ES
2137277    DE
Name: country_code, dtype: object
id
18666        Spain
2137277    Germany
Name: country, dtype: object
id
18666      Entire home/apt
21605         Private room
8521278        Shared room
Name: room_type, dtype: object
id
18666        6
18674        8
21605        2
31380        3
31958        4
32471        5
34981       10
35388        1
50066        9
67065        7
73683       12
474387      11
261750      13
478616      16
1098894     14
16938522    15
Name: accommodates, dtype: int64
id
18666        1.0
18674        2.0
32471        1.5
34981        3.0
71520        4.0
183858       NaN
186221       0.0
256982       0.5
267816       4.5
425639       3.5
478616      16.0
544995       2.5
1098894      6.0
1305640      5.0
4200509      7.5
5056503      5.5
6318322      8.0
6670509      7.0
25095570    10.0
26387202     6.5
28178316    13.5
28170986     8.5
Name: bathrooms, dtype: float64
id
18666        2.0
18674        3.0
21605        1.0
34981        4.0
186540       0.0
474387       5.0
478616      16.0
531851       6.0
1580586      NaN
2144561     12.0
4200509      8.0
4996306      7.0
5056503      9.0
5793703     10.0
19217531    11.0
28329821    13.0
Name: bedrooms, dtype: float64
id
18666        4.0
18674        6.0
21605        1.0
31377        2.0
32471        3.0
32711        7.0
34981        8.0
71520        5.0
73683       14.0
474387      11.0
261750      10.0
275346       0.0
478616      16.0
531195       9.0
640130       NaN
927680      18.0
1005420     12.0
1215339     15.0
2144561     26.0
5056503     17.0
5767967     13.0
7941564     32.0
9246065     28.0
9269020     36.0
9311521     20.0
17486994    48.0
17504672    40.0
29536461    50.0
Name: beds, dtype: float64
id
18666           Real Bed
6464311            Futon
72436      Pull-out Sofa
267816             Couch
1139564           Airbed
Name: bed_type, dtype: object
id
18666        2
21605        1
31380        3
31823        6
32711        4
32868        8
67065        7
163448       5
531195      12
872568      16
959880      10
1129827     11
2308287      9
8351864     15
10737758    13
13666450    14
Name: guests_included, dtype: int64
id
18666       10.0
18674        9.0
26033978     NaN
46153        6.0
71520        8.0
180293       2.0
242335       7.0
11660315     4.0
6667181      5.0
9560761      3.0
Name: review_scores_accuracy, dtype: float64
id
18666       10.0
21605        9.0
26033978     NaN
46153        6.0
61444        8.0
73700        7.0
3431763      5.0
6382022      2.0
11108766     4.0
29004457     3.0
Name: review_scores_cleanliness, dtype: float64
id
18666        2.0
18674       10.0
31380        9.0
26033978     NaN
46153        6.0
180293       8.0
705086       7.0
7262469      4.0
16059107     3.0
25972421     5.0
Name: review_scores_checkin, dtype: float64
id
18666       10.0
31380        9.0
26033978     NaN
46153        7.0
73643        8.0
705086       5.0
1106731      6.0
26083596     4.0
6382022      2.0
9412798      3.0
Name: review_scores_communication, dtype: float64
id
18666       10.0
18674        9.0
31380        8.0
26033978     NaN
46153        7.0
3346354      6.0
12075630     4.0
13427408     2.0
25244815     5.0
Name: review_scores_location, dtype: float64
id
18666        8.0
18674        9.0
26033978     NaN
35390       10.0
46153        6.0
180293       2.0
261750       7.0
2054129      5.0
7879007      4.0
25972421     3.0
Name: review_scores_value, dtype: float64
id
18666    f
Name: is_business_travel_ready, dtype: object
id
18666                         flexible
18674      strict_14_with_grace_period
21605                         moderate
531195                 super_strict_30
569527                 super_strict_60
2252210                         strict
Name: cancellation_policy, dtype: object
id
18666    f
25786    t
Name: require_guest_profile_picture, dtype: object
id
18666    f
25786    t
Name: require_guest_phone_verification, dtype: object

In [46]:
print(tmp)

['listing_url:42094', 'name:40957', 'summary:38085', 'space:27385', 'description:40245', 'neighborhood_overview:21414', 'notes:14626', 'transit:22125', 'access:18965', 'interaction:17368', 'house_rules:20222', 'picture_url:41820', 'user_id:26659', 'host_url:26659', 'user_name:8291', 'host_since:2986', 'host_about:13783', 'host_response_time:5', 'host_response_rate:70', 'host_thumbnail_url:26590', 'host_picture_url:26590', 'host_neighbourhood:222', 'host_verifications:378', 'neighbourhood:224', 'city:74', 'country_code:2', 'country:2', 'latitude:42094', 'longitude:42094', 'property_type:37', 'room_type:3', 'accommodates:16', 'bathrooms:22', 'bedrooms:16', 'beds:28', 'bed_type:5', 'amenities:37765', 'square_feet:162', 'price:447', 'weekly_price:551', 'monthly_price:685', 'security_deposit:223', 'cleaning_fee:156', 'guests_included:16', 'extra_people:82', 'minimum_nights:112', 'maximum_nights:311', 'review_scores_rating:52', 'review_scores_accuracy:10', 'review_scores_cleanliness:10', 'review_scores_checkin:10', 'review_scores_communication:10', 'review_scores_location:9', 'review_scores_value:10', 'is_business_travel_ready:1', 'cancellation_policy:6', 'require_guest_profile_picture:2', 'require_guest_phone_verification:2']

In [28]:
amenities = listings.amenities.apply(lambda x: x[1:-1].replace('"',"").split(',')).values.flatten()
amenities = [amenity for lst in amenities for amenity in lst]
amenities = list(dict.fromkeys(amenities))
amenities = list(filter(None, amenities))

In [31]:
amenities = pd.DataFrame(amenities)
amenities.head

<bound method NDFrame.head of                               0
0                            TV
1                      Internet
2                          Wifi
3              Air conditioning
4         Wheelchair accessible
5                       Kitchen
6                      Elevator
7           Free street parking
8                       Heating
9           Family/kid friendly
10                       Washer
11                        Dryer
12                   Essentials
13                      Shampoo
14                   Hair dryer
15                    Hot water
16              Host greets you
17     Paid parking on premises
18     Buzzer/wireless intercom
19                      Hangers
20                         Iron
21    Laptop friendly workspace
22                         Crib
23    Paid parking off premises
24                First aid kit
25                Self check-in
26                   Smart lock
27                   Bed linens
28   Extra pillows and blankets
29                    Microwave
..                          ...
151                Air purifier
152               Mountain view
153                Sound system
154                  Steam oven
155            Private bathroom
156                  DVD player
157                Sun loungers
158                 Mini fridge
159                Private pool
160                 Wine cooler
161                  Jetted tub
162    Central air conditioning
163                     Hammock
164             Outdoor parking
165                  Murphy bed
166  Fixed grab bars for toilet
167           Touchless faucets
168                 Amazon Echo
169              Warming drawer
170        Projector and screen
171        Pool with pool hoist
172                  Shared gym
173                  Pool cover
174                 Lake access
175               Heated floors
176                Mobile hoist
177                       Sauna
178                 Fax machine
179         Ground floor access
180               Ceiling hoist

[181 rows x 1 columns]>

In [8]:
list3 = [item for x in tmp for item in x]

In [13]:
len(list3)

182

In [12]:
list3 = list(dict.fromkeys(list3))

In [58]:
find_different_objects(listings, 'city', True)

id
18666                                Barcelona
1005751                              barcelona
577865                         08014 BARCELONA
637232                               Барселона
8521278                             Barcelona
811918                 Hospitalet de Llobregat
896337                          Barcelonaneta
1026452                                    NaN
2388976                          Eixample (L')
2438814             Sagrada Familia, Barcelona
3107710                              BARCELONA
3664007                             Barcellona
4090521                              Barcelone
8420515              L'Hospitalet de Llobregat
9806352                    Sant Adrià de Besòs
11136572      Barcelona (Metro L1) Hostafrancs
13682702                        BARCELONA CLOT
14362758              Barcelona, Catalunya, ES
15636856                            Zona Forum
17390030                   Sant Adrià de Besos
17469203                             Catalonia
21376942                              Barcelon
23931385                      08028, Barcelona
26410641                                 Spain
26940439                              Eixample
2137277                                 Berlin
2168295                           Berlin Mitte
2443247                  Berlin-Friedrichshain
2507059     Baseler Straße 91 A, 12205 Berlin
2658547                        Berlin-Neukölln
                           ...
6691656                     Berlin-Wilmersdorf
6790425                                Wannsee
6863979                     Berlin, Schöneberg
7397679                                 berlin
7737292                       Berlin (Wedding)
7800129                       Mitte/Tiergarten
8520472                         Friedrichshain
9543073                               Köpenick
11286857                       Mitte/Kreuzberg
11294384                 Berlin Friedrichshain
12463315         SavignyPlatz (Charlottenburg)
167189                      Berlin (Kreuzberg)
1198030                         Berlin-Wedding
1814192                           Berlin-Mitte
2019132                            Woltersdorf
2043979                         Berlin-Treptow
2075180                      Berlin-Schöneberg
19864                                   Madrid
814586                                  MADRID
1044902                                  Chiva
2731796                         Centro, Madrid
2847041                                 Centro
4348499                                 madrid
5602310                                Madrid
5925522                         Chueca, Madrid
11645634                         Apartment 3-I
11956508                            San Lázaro
17042796       Madrid, Comunidad de Madrid, ES
17455814                    Pozuelo de Alarcón
23675842                               Aravaca
Name: city, Length: 74, dtype: object

74